volumes:
  specialist-publisher-tmp:
  specialist-publisher-node-modules:

x-specialist-publisher: &specialist-publisher
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: specialist-publisher
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - specialist-publisher-tmp:/govuk/specialist-publisher/tmp
    - specialist-publisher-node-modules:/govuk/specialist-publisher/node_modules
  working_dir: /govuk/specialist-publisher

services:
  specialist-publisher-lite:
    <<: *specialist-publisher
    shm_size: 512mb
    depends_on:
      - mysql-8
      - specialist-publisher-redis
    environment:
      DATABASE_URL: "mysql2://root:root@mysql-8/specialist_publisher_development"
      TEST_DATABASE_URL: "mysql2://root:root@mysql-8/specialist_publisher_test"
      REDIS_URL: redis://specialist-publisher-redis

  specialist-publisher-app: &specialist-publisher-app
    <<: *specialist-publisher
    depends_on:
      - mysql-8
      - specialist-publisher-redis
      - nginx-proxy
      - publishing-api-app
      - asset-manager-app
      - email-alert-api-app
      - specialist-publisher-worker
    environment:
      DATABASE_URL: "mysql2://root:root@mysql-8/specialist_publisher_development"
      REDIS_URL: redis://specialist-publisher-redis
      VIRTUAL_HOST: specialist-publisher.dev.gov.uk
      BINDING: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart

  specialist-publisher-worker:
    <<: *specialist-publisher
    depends_on:
      - mysql-8
      - specialist-publisher-redis
      - publishing-api-app
      - asset-manager-app
    environment:
      DATABASE_URL: "mysql2://root:root@mysql-8/specialist_publisher_development"
      REDIS_URL: redis://specialist-publisher-redis
    command: bundle exec sidekiq -C ./config/sidekiq.yml

  specialist-publisher-redis:
    image: redis